In [ ]:
import sys
import os

sys.path.append(os.path.abspath(".."))

from utils import plot_df_chart, describe_data, get_frequency_table, load_report_data

In [18]:
DICT = {
    "GDPC1": {
        "title": "Real Gross Domestic Product",
        "unit": "Billions of Chained 2017 Dollars"
    },
    "GDP": {
        "title": "Gross Domestic Product",
        "unit": "Billions of Dollars"
    },
}

In [19]:
INDICATOR = 'GDPC1'

COL = '% change'

In [20]:
df = load_report_data(INDICATOR)

# df[COL] = df[INDICATOR].pct_change(fill_method=None) * 100
df[COL] = (df[INDICATOR].ffill().pct_change() * 100)

df.dropna(inplace=True)

df.tail()

           DATE      GDPC1  % change
311  2024-10-01  23586.542  0.459875
312  2025-01-01  23548.210 -0.162516
313  2025-04-01  23770.976  0.946000
314  2025-07-01  24026.834  1.076346
315  2025-10-01  24111.830  0.353754

- **Stats**

In [21]:
df_stats, stats = describe_data(df[COL])

df_stats

              Value
Metric
nobs            315
Min %     -7.876784
Max %      7.762279
Mean %      0.77164
Median %   0.773092
Mode %    -7.876784
Variance   1.233066
Skewness  -0.728561
Kurtosis  15.955991

In [22]:
freq_table = get_frequency_table(df[COL])

freq_table

                    Frequency  Probability %  Cumulative Probability %
Less than -5.27%            1       0.318471                  0.318471
-5.27% to -2.66%            0       0.000000                  0.318471
-2.66% to -0.06%           43      13.694268                 14.012739
-0.06% to 2.55%           263      83.757962                 97.770701
2.55% to 5.16%              7       2.229299                100.000000
Greater than 5.16%          0       0.000000                100.000000

In [23]:
fig = plot_df_chart(
    freq_table[['Probability %']],
    chart_title = f'{DICT[INDICATOR]['title']} (% change frequency)',
    chart_type = "bar",
    yaxis_title = "Probability %",
    width=1000,
    height=700,
    show_rangeslider=False
)

In [ ]:
import plotly.graph_objects as go

fig = plot_df_chart(
    df[[COL]],
    chart_title = DICT[INDICATOR]["title"] + f' ({COL})',
    chart_type = "bar",
    yaxis_title = "%",
    draw=False,
)

AVG_PERIOD = 12 * 10

fig.add_trace(go.Scatter(
    x=df.index,
    y=df[COL].rolling(window=AVG_PERIOD).mean(),
    name='Average ' + COL + f' ({AVG_PERIOD} months)',
    line=dict(
        width=1,
        color="#F2C14E",
        # dash="dash"
    ),
    # hoverinfo="skip",
    # showlegend=False,
))

fig.show()

- **Plot of Data**

In [25]:
plot_df_chart(
    df[[INDICATOR]],
    chart_title=DICT[INDICATOR]['title'],
    yaxis_title=DICT[INDICATOR]['unit'],
    use_markers=False
)