In [82]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [83]:
import pandas as pd
from utils import DATA_FOLDER_PATH, plot_df_chart, describe_data, get_frequency_table
import os

In [84]:
DICT = {
    "GDPC1": {
        "title": "Real Gross Domestic Product",
        "unit": "Billions of Chained 2017 Dollars"
    },
    "GDP": {
        "title": "Gross Domestic Product",
        "unit": "Billions of Dollars"
    },
}

In [85]:
INDICATOR = 'GDPC1'

COL = '% change'

In [86]:
df = pd.read_csv(os.path.join(DATA_FOLDER_PATH, INDICATOR + '.csv'))

df['DATE'] = pd.to_datetime(df['DATE'])
df.set_index('DATE', inplace=True)

# df[COL] = df[INDICATOR].pct_change(fill_method=None) * 100
df[COL] = (df[INDICATOR].ffill().pct_change() * 100)

df.dropna(inplace=True)

df.tail()

                GDPC1  % change
DATE
2024-07-01  23478.570  0.824778
2024-10-01  23586.542  0.459875
2025-01-01  23548.210 -0.162516
2025-04-01  23770.976  0.946000
2025-07-01  24026.834  1.076346

- **Stats**

In [87]:
df_stats, stats = describe_data(df[COL])

df_stats

              Value
Metric
nobs            314
Min %     -7.876784
Max %      7.762279
Mean %     0.772971
Median %   0.773805
Mode %    -7.876784
Variance   1.236446
Skewness  -0.731324
Kurtosis  15.916359

In [88]:
freq_table = get_frequency_table(df[COL])

freq_table

                    Frequency  Probability %  Cumulative Probability %
Less than -5.27%            1       0.319489                  0.319489
-5.27% to -2.66%            0       0.000000                  0.319489
-2.66% to -0.06%           43      13.738019                 14.057508
-0.06% to 2.55%           262      83.706070                 97.763578
2.55% to 5.16%              7       2.236422                100.000000
Greater than 5.16%          0       0.000000                100.000000

In [89]:
fig = plot_df_chart(
    freq_table[['Probability %']],
    chart_title = f'{DICT[INDICATOR]['title']} (% change frequency)',
    chart_type = "bar",
    yaxis_title = "Probability %",
    width=1000,
    height=700,
    show_rangeslider=False
)

In [90]:
fig = plot_df_chart(
    df[[COL]],
    chart_title = DICT[INDICATOR]["title"] + f' ({COL})',
    chart_type = "bar",
    yaxis_title = "%",
    draw=False,
)

AVG_PERIOD = 12 * 10

fig.add_trace(go.Scatter(
    x=df.index,
    y=df[COL].rolling(window=AVG_PERIOD).mean(),
    name='Average ' + COL + f' ({AVG_PERIOD} months)',
    line=dict(
        width=1,
        color="#F2C14E",
        # dash="dash"
    ),
    # hoverinfo="skip",
    # showlegend=False,
))

fig.show()

- **Plot of Data**

In [91]:
plot_df_chart(
    df[[INDICATOR]],
    chart_title=DICT[INDICATOR]['title'],
    yaxis_title=DICT[INDICATOR]['unit'],
    use_markers=False
)