In [1]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [2]:
import plotly.graph_objects as go
from utils import load_report_data, describe_data, get_frequency_table, plot_df_chart

In [3]:
DICT = {
    "CPIAUCSL": {
        "title": "Consumer Price Index for All Urban Consumers: All Items in U.S. City Average",
        "unit": ""
    },
    "CPILFESL": {
        "title": "Consumer Price Index for All Urban Consumers: All Items Less Food and Energy in U.S. City Average",
        "unit": ""
    },
    "WPSFD49207": {
        "title": "Producer Price Index by Commodity: Final Demand: Finished Goods",
        "unit": ""
    },
    "WPSFD4131": {
        "title": "Producer Price Index by Commodity: Final Demand: Finished Goods Less Foods and Energy",
        "unit": ""
    },
    "PCEPILFE": {
        "title": "Personal Consumption Expenditures Excluding Food and Energy (Chain-Type Price Index)",
        "unit": ""
    },
    "PCEPI": {
        "title": "Personal Consumption Expenditures: Chain-type Price Index",
        "unit": ""
    },
}

In [4]:
INDICATOR = 'WPSFD49207'

MoM_col = 'MoM ^ %'
YoY_col = 'YoY ^ %'

COL = YoY_col

In [5]:
df = load_report_data(INDICATOR)


# df[COL] = df[INDICATOR].pct_change(fill_method=None, periods=12 if COL == YoY_col else 1) * 100

df[COL] = df[INDICATOR].ffill().pct_change(periods=12 if COL == YoY_col else 1) * 100

df.tail()

           DATE  WPSFD49207   YoY ^ %
939  2025-07-01     262.510  2.033598
940  2025-08-01     262.787  1.991415
941  2025-09-01     265.516  3.103000
942  2025-10-01     263.829  2.512803
943  2025-11-01     266.904  2.869432

- **Stats**

In [6]:
df_stats, stats = describe_data(df[COL].dropna())

df_stats

              Value
Metric
nobs            932
Min %      -6.48855
Max %     19.491525
Mean %     3.052466
Median %   2.419851
Mode %          0.0
Variance  16.217073
Skewness   1.159418
Kurtosis   1.649973

- **Freq**

In [7]:
freq_table = get_frequency_table(df.dropna()[COL])

freq_table

                     Frequency  Probability %  Cumulative Probability %
Less than -2.16%            42       4.506438                  4.506438
-2.16% to 2.17%            398      42.703863                 47.210300
2.17% to 6.5%              347      37.231760                 84.442060
6.5% to 10.83%              82       8.798283                 93.240343
10.83% to 15.16%            54       5.793991                 99.034335
Greater than 15.16%          9       0.965665                100.000000

In [8]:
fig = plot_df_chart(
    freq_table[['Probability %']],
    chart_title = f'{DICT[INDICATOR]['title']} (% change frequency)',
    chart_type = "bar",
    yaxis_title = "Probability %",
    width=1000,
    height=700,
    show_rangeslider=False
)

In [9]:
fig = plot_df_chart(
    df[[COL]],
    chart_title = DICT[INDICATOR]["title"] + f' ({COL})',
    chart_type = "bar",
    yaxis_title = "%",
    draw=False,
)

AVG_PERIOD = 12 * 5

fig.add_trace(go.Scatter(
    x=df.index,
    y=df[COL].rolling(window=AVG_PERIOD).mean(),
    name='Average ' + COL + f' ({AVG_PERIOD} months)',
    line=dict(
        width=1,
        color="#F2C14E",
        # dash="dash"
    ),
    # hoverinfo="skip",
    # showlegend=False,
))

fig.show()

- **plot data**

In [10]:
plot_df_chart(
    df[[INDICATOR]],
    chart_title = DICT[INDICATOR]["title"],
    yaxis_title = DICT[INDICATOR]["unit"],
    use_markers=False
)