In [11]:
import sys
import os

sys.path.append(os.path.abspath(".."))

In [ ]:
from utils import load_report_data, plot_df_chart, describe_data, get_frequency_table

In [13]:
DICT = {
    "PAYEMS": {
        "title": "All Employees, Total Nonfarm (NFP)",
        "unit": "Thousands of Persons"
    },
    "UNRATE": {
        "title": "Unemployment Rate",
        "unit": "%"
    },
}

In [14]:
INDICATOR = 'UNRATE'

MoM_col = 'MoM ^ %'
YoY_col = 'YoY ^ %'

COL = YoY_col

In [15]:
df = load_report_data(INDICATOR)

# df[COL] = df[INDICATOR].pct_change(fill_method=None, periods=12 if COL == YoY_col else 1) * 100

df[COL] = df[INDICATOR].ffill().pct_change(periods=12 if COL == YoY_col else 1) * 100

df.tail()

            UNRATE   YoY ^ %
DATE
2025-09-01     4.4  7.317073
2025-10-01     NaN  7.317073
2025-11-01     4.5  7.142857
2025-12-01     4.4  7.317073
2026-01-01     4.3  7.500000

- **Plot of Data**

In [16]:
plot_df_chart(
    df[[INDICATOR]],
    chart_title=DICT[INDICATOR]['title'],
    yaxis_title=DICT[INDICATOR]['unit'],
    use_markers=False
)

- **Stats**

In [17]:
df_stats, stats = describe_data(df[COL].dropna())

df_stats

               Value
Metric
nobs             925
Min %     -58.783784
Max %          300.0
Mean %      3.398308
Median %   -5.084746
Mode %           0.0
Variance  925.040958
Skewness    3.381712
Kurtosis   20.474658

In [18]:
freq_table = get_frequency_table(df.dropna()[COL])

freq_table

                     Frequency  Probability %  Cumulative Probability %
Less than 1.01%            604      65.367965                 65.367965
1.01% to 60.81%            270      29.220779                 94.588745
60.81% to 120.61%           40       4.329004                 98.917749
120.61% to 180.41%           7       0.757576                 99.675325
180.41% to 240.2%            1       0.108225                 99.783550
Greater than 240.2%          2       0.216450                100.000000

In [19]:
fig = plot_df_chart(
    freq_table[['Probability %']],
    chart_title = f'{DICT[INDICATOR]['title']} (% change frequency)',
    chart_type = "bar",
    yaxis_title = "Probability %",
    width=1000,
    height=700,
    show_rangeslider=False
)

In [ ]:
import plotly.graph_objects as go

fig = plot_df_chart(
    df[[COL]],
    chart_title = DICT[INDICATOR]["title"] + f' ({COL})',
    chart_type = "bar",
    yaxis_title = "%",
    draw=False,
)

AVG_PERIOD = 12 * 10

fig.add_trace(go.Scatter(
    x=df.index,
    y=df[COL].rolling(window=AVG_PERIOD).mean(),
    name='Average ' + COL + f' ({AVG_PERIOD} months)',
    line=dict(
        width=1,
        color="#F2C14E",
        # dash="dash"
    ),
    # hoverinfo="skip",
    # showlegend=False,
))

fig.show()